"""Frozen scenario banks (§10.1): generated once, admission-filtered, frozen
to JSON, versioned.  scenario_id = SHA256(generator_version || seed).  The
admission rate over the scanned seed range is logged into the bank file.
"""
from __future__ import annotations

import json
from pathlib import Path

from ..core.scenario import Scenario
from .admit import admit
from .generate import GENERATOR_VERSION, generate

REPO_ROOT = Path(__file__).resolve().parents[3]
BANKS_DIR = REPO_ROOT / "banks"


def build_bank(n_scenarios: int, start_seed: int = 0, max_seeds: int = 100_000):
    """Scan seeds from start_seed until n_scenarios are admitted.  Returns
    (scenarios, stats)."""
    admitted: list[Scenario] = []
    tried = 0
    for seed in range(start_seed, start_seed + max_seeds):
        tried += 1
        sc = generate(seed)
        rep = admit(sc)
        if rep.admitted:
            admitted.append(sc)
            if len(admitted) >= n_scenarios:
                break
    stats = {
        "generator_version": GENERATOR_VERSION,
        "seeds_tried": tried,
        "admitted": len(admitted),
        "admission_rate": len(admitted) / tried if tried else 0.0,
    }
    return admitted, stats


def freeze_bank(name: str, scenarios: list[Scenario], stats: dict) -> Path:
    BANKS_DIR.mkdir(exist_ok=True)
    path = BANKS_DIR / f"{name}.json"
    payload = {
        "bank_id": name,
        "generator_version": GENERATOR_VERSION,
        "stats": stats,
        "scenarios": [sc.to_dict() for sc in scenarios],
    }
    path.write_text(json.dumps(payload, indent=1, sort_keys=True) + "\n",
                    encoding="utf-8", newline="\n")
    return path


def load_bank(name: str) -> list[Scenario]:
    """Load a frozen bank; each scenario is expanded into both seat orders
    (opening mover 1 and 2), giving 2x templates."""
    path = BANKS_DIR / f"{name}.json"
    payload = json.loads(path.read_text(encoding="utf-8"))
    if payload["generator_version"] != GENERATOR_VERSION:
        raise ValueError(
            f"bank {name} was generated by {payload['generator_version']}, "
            f"current is {GENERATOR_VERSION}: refused, not coerced")
    out = []
    for d in payload["scenarios"]:
        sc = Scenario.from_dict(d)
        out.append(sc)
        out.append(sc.with_opening(3 - sc.opening))
    return out


def bank_stats(name: str) -> dict:
    path = BANKS_DIR / f"{name}.json"
    return json.loads(path.read_text(encoding="utf-8"))["stats"]
